spring.application.name=AI_Powered_Resume_Screening_Assistant
spring.datasource.url=jdbc:postgresql://localhost:5432/resume_ai
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080